### ISSUE TITLE
Submission Review

### ISSUE THREAD

**Issue by ivan-adakerja** [septianppm/fb-bot-nodejs-webhook-and-restapi-v2#1]
Hi @septianppm ! I am Ivan 👋 😄 from AdaKerja
Thanks for the submission, here I have my review result for you.

- [+] run on production
- [+-] good it have folder separation. but it doesn't have consistency, message have controller but webhook doesn't
- [-] no code format, bit hard to read. many repeated code, example [multiple lowercase](https://github.com/septianppm/fb-bot-nodejs-webhook-and-restapi-v2/blob/main/routes/webhook.routes.js#L45)
- [-] setup not clear. hard to locate all env. also config like [this hostname](https://github.com/septianppm/fb-bot-nodejs-webhook-and-restapi-v2/blob/main/routes/webhook.routes.js#L72) should be put in env
- [+] use db - mysql for messages
- [-] state is bad, is based on user message. we can't control the flow (name -> birthday -> calculate / bye)
    - if user say 'hi' all times bot can't continue
    - use in memory and shared variable, if 2 user chat at the same time it could cause race condition
    - introducing new bot question will be hard
- [-] [birthday calculation wrong](https://user-images.githubusercontent.com/70680973/153732208-951f43b5-c56b-49c5-8847-72279a9ba891.png)

**Comment by septianadg** [comment]
Ok, I will try to fix this issue after my COVID-19 self-isolation period ends.

thank you

regards
Septian

**Comment by septianadg** [comment]
Dear Ivan,

Please review, I've updated to fix the points:
- it doesn't have consistency, message have controller but webhook doesn't
- no code format, bit hard to read. many repeated code, example multiple lowercase
- setup not clear. hard to locate all env. also config like this hostname should be put in env
- birthday calculation wrong

However, I'm still confused on the points:
- state is bad, is based on user messages.
- use in memory and shared variable, if 2 user chat at the same time it could cause race condition
Can you give me an example or a clue?

thank you,

Regards
Septian

**Comment by ivan-adakerja** [comment]
eyo @septianppm 

Saw some commits & updates there:

- You move the webhook controller, but you update .env on old webhook https://github.com/septianppm/fb-bot-nodejs-webhook-and-restapi-v2/commit/c7f8b813e139a954de7e226a38b39990b23195d1 . Also better to have something like `.env.example` to keep track all of your env 
- Calculation still wrong, lets say user's birthday is on 10 January, it return with negative. [here another test](https://user-images.githubusercontent.com/70680973/154393272-b649e634-5721-4aed-9d7c-0a0f1bc88b4d.png)

---

For the points:

- Why I say state is bad when its based on user messages, lets say we want to introduce new question something like "Do you live in Indonesia?". With your current code we need to refactor it, its not scalable.
- So for race conditions, this occurred because you have [in memory variable `nextbirthday` here](https://github.com/septianppm/fb-bot-nodejs-webhook-and-restapi-v2/blob/main/controllers/webhook.controller.js#L6). Lets say you have 2 users, user A and B :
  - User A input 31 December to bot. `nextbirthday = 31 December`
  - User B input 31 January to bot. now `nextbirthday = 31 January`
  - User A answer yes to bot to show birthday calculation. Bot will calculating from user B's input thus will show incorrect things to user A
